### ISSUE TITLE
Week 2 Project Review Ticket

### ISSUE THREAD

**Issue by lucasho22** [jacksongolding/Nut-Team#14]
- [ ] Project Owner / Sponsor presentation(visuals like wireframes or HTML pages), results of review, PII concerns, hosting plan, and software license

- [ ] 1st Code in GitHub with software license per 5.5

**Comment by lucasho22** [comment]
- What APIs could you use in the project? Could you use APIs for the project?

**Comment by ChaseOtt** [comment]
2/2
Their project was well explained.
